### ISSUE TITLE
Update selenide dependency 

### ISSUE THREAD

**Issue by Maxon4eg** [erolstt/selenoid-selenide-example#1]
Hello
Tried to run tests
got an error
```
Error:(8, 38) java: cannot access org.openqa.selenium.internal.Locatable
  class file for org.openqa.selenium.internal.Locatable not found

```
after updating selenide dependency to  **com.codeborne:selenide:4.4.3**  error was fixed 
just for info :)

**Comment by erolstt** [comment]
Hi @Maxon4eg ,

Thank you for letting me know. I will update selenide version.

**Comment by erolstt** [comment]
upgraded to latest version of selenide
